- RLTest/__main__.py
- RLTest/env.py
- add a setup/teardown feature
- better cleanup for `--exit-on-failure`
- allow for a `message` argument in most `assert()` functions
> some minor fixes & additions:

- RLTest/__main__.py
This can be used with leak sanitizer
> Add option (--check-exitcode) to ensure process always exits cleanly

- RLTest/__main__.py
- RLTest/env.py
- RLTest/redis_std.py
To be able to run ctest with the -j flag
> Some fixes for concurrent operation

- RLTest.sh
- RLTest/__init__.py
- RLTest/__main__.py
- RLTest2.sh
- RLTest3.sh
- requirements.txt
- RLTest*.sh scripts to run RLTest on a clean environment,
- Disabled python deprecation warnings,
- Added upper bound on redis-py package.
> Added installation/venv scripts

- RLTest/__main__.py
- RLTest/env.py
- RLTest/redis_enterprise_cluster.py
Some additional changes (to be able to communicate with shards) 
i made some inner imports "requests" and "urllib3" . It should not fail in case you run it locally(cause the import is inside bind method)
But:
1. if you want to run the tests from private PC on real cluster you have to have it on PC 
2. import within method is not so good, In order to solve it we have to insert the "reqiuests" lib to dependencies
> Get nodes IP's , to init shards clients

- RLTest/redis_cluster.py
Due to change in redis-py-cluster.
> StrictRedisCluster -> RedisCluster

- RLTest/__main__.py
Avoid quoting woes when using --vg-options
> Accept Valgrind options via VG_OPTIONS env var

- .github/workflows/ci.yml
- RLTest/redis_cluster.py
- tests/flow/test_simple_flow.py
- tests/unit/test_env.py
- tests/unit/test_redis_cluster.py
- tests/unit/test_redis_std.py
refering https://github.com/Grokzen/redis-py-cluster/issues/260
-  [add] hardened tls tests ( skipping when cert files are not present )
-  [fix] workaround on ssl cluster connection
> Fix tests tls

- .github/workflows/ci.yml
This PR enabled nightly tests on RLTest
> Run ci nightly

- RLTest/env.py
- RLTest/redis_cluster.py
- RLTest/redis_std.py
- tests/unit/test_redis_std.py
this PR allows to close specific roles in the environment, so it will allow testing short reads during master<->slaves syncs
> close specific role in the env

- .github/workflows/ci.yml
- README.md
- RLTest/__main__.py
- RLTest/env.py
- RLTest/redis_std.py
- pyproject.toml
- tests/unit/test_redis_std.py
Add the option to use aof without RDB preamble, to test that a module performs aof rewrite properly.
> Add use rdb preamble flag

- RLTest/random_port.py
can't modify dict while iterating over it
> remove unresponsive processes from ports file

- RLTest/__main__.py
- RLTest/env.py
> Fixed python2 -> python3 raw_input change

- RLTest/redis_std.py
Fixes #107 
Related to issues on: (build_and_package) in RedisBloom/RedisBloom (master)
https://circleci.com/gh/RedisBloom/RedisBloom/3313?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
> [fix] Fix for flaky tests due to SAVE -> DEBUG RELOAD

- .github/workflows/publish-pypi.yml
- pyproject.toml
- Changing pypi publish to follow the build method
> Pypi publish update

- RLTest/__main__.py
- RLTest/env.py
- RLTest/redis_cluster.py
- RLTest/redis_std.py
The information collected:
1. Info command from all the shards.
2. Logs of all the shards.
3. stdout and stderr of all the shards.
> Added the option to collect usefull information on failure and print it to stdout.

- RLTest/__main__.py
- RLTest/env.py
- RLTest/redis_std.py
- pyproject.toml
added `--log-level` attribute to set the server log level
> loglevel config

- .github/workflows/ci.yml
This PR fixes poetry to 1.5.1 which is the latest that supports python 3.7
> poetry 1.5.1

- .github/workflows/publish-pypi.yml
- pyproject.toml
1. improved version getter
2. set the master version to `99.99.99` so we won't need to maintain it anymore
> improved and enhanced release flow

- RLTest/__main__.py
- RLTest/redis_std.py
A followup for #219
passing the `cwd` for the slave process as well
> Fix slave's log directory

- README.md
- RLTest/__main__.py
- RLTest/env.py
- RLTest/redis_std.py
- tests/flow/test_simple_flow.py
- tests/unit/test_redis_std.py
Add new argument to support path to redis configuration file
> Add redis-config-file argument

- RLTest/redis_std.py
https://docs.python.org/3/library/exceptions.html#FileNotFoundError
> Fix the double panic
