RedisLabsModules/RLTest

RLTest/redis_std.py

Overriding LD_LIBRARY_PATH prevents user from setting his own.

LD_LIBRARY_PATH: append rather than override

---

RLTest/utils.py

File "/home/circleci/project/venv/lib/python3.6/site-packages/RLTest/utils.py", line 17, in wait_for_conn
raise Exception('Cannot establish connection %s: %s' % (conn, err))
UnboundLocalError: local variable 'err' referenced before assignment

Fix: local variable 'err' referenced before assignment

---

RLTest/__main__.py

If a cluster node crashes, don't crash again in trying to flush all the
nodes. Ensure all child processes are killed

Clean up all cluster processes on shutdown

---

.github/workflows/ci.yml
RLTest/Enterprise/binaryrepo.py
requirements.txt
setup.py

Given that on python3.8 the platform package has removed the deprecated `platform.distro()` we should follow the recommended alternative distro package.
This PR addresses it, and fixes #77

Fixed python3.8 issue with platform package

---

.github/release-drafter-config.yml
.github/workflows/check-pypi.yml
.github/workflows/publish-pypi.yml
.github/workflows/release-drafter.yml
setup.py

This PR simplifies and automates the release using github actions instead of circleci.
It also includes a check to ensure that the secrets that we're required to have for publishing the packages are set on the repo.

Preparing for release automation 

---

RLTest/env.py
RLTest/redis_cluster.py
RLTest/redis_std.py

This PR allows the user to specify the `decode_responses` argument when building a Redis connection.
This simplifies Python 3 compatibility for RedisGraph.

Add decodeResponse argument to Env

---

RLTest/__main__.py

When we have the --clear-logs option enabled RLTest will always try to delete the logs dir even if does not exist causing a ugly error message ( no harm given it continues ):
Example:
```
MODULE=/root/project/bin/linux-x64-release/****************** \
CLUSTER=0 \
GEN=1 AOF=1 SLAVES=1 \
VALGRIND= \
../tests/flow/tests.sh
[Errno 2] No such file or directory: './logs'
test_ooo:test_ooo
[PASS]
```
This is an easy fix that checks if the dir exists prior deleting it. 
cc @danni-m

Fix: Only removing logs dir on --clear-logs option when it exists

---

.github/workflows/ci.yml
RLTest/__init__.py
RLTest/__main__.py
RLTest/_version.py
setup.py
tests/unit/test_common.py

- Add and expose at runtime in a standard format the __version__ attribute
- fix codecov issue with commit depth
- Reduced timeout from 6 hours to 10min for the entire CI workflow. Set timeout of 5min for unit tests.  Here's a discussion on how to standardize this info: https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

CI timeout improvements and codecov fixes; Add and expose at runtime in a standard format the __version__ attribute

---

setup.py

This PR fixes the added dependency RLTest while installing RLTest.

Fixed the circular depedency of RLTest within setup.py

---

RLTest/redis_std.py

1. On env start, wait until master/slave finishes the first AOF rewrite before accepting commands.
2. Retry terminating redis process instead of trying once, as it might not actually exits (due to writing AOF at this time for example).

Fixes for using AOF+slaves

---

RLTest/redis_std.py

Call _waitForAOFChild() both before and after bgrewriteaof() to avoid conjunctions of AOF rewrite

AOF+slaves fix 2

---

RLTest/debuggers.py
tests/unit/test_debuggers.py

Since Redis 6.2, redis will not allow saving when RDB failed to save. When using valgrind on forks, it may return an error code. We will use 255 error code in valgrind so in case of forked process failure, redis will ignore this value and cwill not treat it as error

valgrind exit code is 255

---

RLTest/__main__.py

The PR adds support for parallel tests execution. It is possible to specify how many parallel tests to run using the new `--parallelism` option (default is 1 as today). Using this flag directly implies random ports (otherwise the tests will not be able
to run in parallel).
When using parallelism greater than 1, RLTest will use python multiprocessing library to run the tests in parallel. In such case, RLTest will create a multiprocessing queue and will put all the test there. Each process will take the next test to run and will execute it until there is no more tests left on the queue. When finished, each process will send the tests results to the main process. The main process will accumulate all the results and will print the final summery.
If parallelism is set to 1, run all the tests …

Added support for parallel tests execution.

---

.github/workflows/ci.yml
RLTest/__main__.py

When parallelism is set to 1 there might be a race condition between the time we add a job to the time we fetch it. To avoid this we set timeout on 0.1 sec to fetch the job.

Fix race condition on multiprocess queue

---

RLTest/__main__.py
RLTest/env.py
RLTest/loader.py

Now that it is possible for tests to run in parallel it require serialize and deserialize the test to another process. For this to work the test must be serializable. Most of the time it works fine but sometimes (for example when tests are used with decorator) it will not work.
Change loader to return a serializable test. The returned object will hold a metadata about the test (file, and symbol). Each processes will use this information to load the test on spot and run it.

Change loader to return serializable objects

---

RLTest/__main__.py
RLTest/env.py

This solves the issue where Redis log files are created with `__init__` when used as test class. The log file will now have the test name.

Match tests name when setting up env.

---

RLTest/__main__.py
RLTest/env.py
RLTest/redis_cluster.py
RLTest/redis_std.py

When parallelism is used, there is no need for random ports. Each processes gets a port to use from the father processes
and keep using it for all the test. This helps to avoid port collision.

Avoid random ports on parallelis.

---

.github/workflows/ci.yml
RLTest/__main__.py
RLTest/env.py
RLTest/redis_cluster.py
RLTest/redis_enterprise_cluster.py
RLTest/redis_std.py
pyproject.toml

Moved to redispy 4.1.3 and add tls-passphrase option
**The PR changes minimum python supported version to 3.6**

Upgrade to redispy 4.1.3 (min python 3.6)

---

RLTest/__main__.py
RLTest/loader.py
RLTest/utils.py
pyproject.toml

`--tests-file` (repeatable) allows for specification of a file containing a list of test specs (`file:test`)
`--failed-tests-file` enables writing of failed tests names into a specified file
Also made `--test` repeatable.

Added --tests-file and --failed-tests-file options

---

RLTest/redis_std.py

if process terminate call in a loop redis did not shutdown cleanly and we see a lot of invalid read in RedisGraph memcheck

call process terminate once

---

.github/workflows/ci.yml
RLTest/redis_std.py

Revert the changes on https://github.com/RedisLabsModules/RLTest/pull/191
It broke valgrind run, this change cause only the first shard on cluster to run with valgrind.

Revert 54d1b81d as it broke valgrind run.

---

.github/workflows/ci.yml

Currently, only one of the matrix sub-jobs is marked as required to pass to approve a PR.
This PR Implements the `pr-validation` job:
- It waits for all the jobs in its `needs` section
- It never skips (only succeeds, fails or cancels)
- it fails if any of its "needed" jobs fails
- if we want additional jobs to be required in the future for PR validation, we just have to add them to the `needs` section
If we make this job the requirement in the repo settings, all the `build` matrix jobs will be required to pass CI.

CI improvement

---

RLTest/loader.py

`imp` is deprecated. RediSearch MacOS CI installs Python 3.12 and can no longer use RLTest if it uses `imp`
This PR replaces the `imp` usage with `importlib.utils` functionality.

Replace imp module with importlib

---

.github/workflows/publish-pypi.yml

1. `::set-output` is deprecated. Changing to the new syntax.
2. simplified step
3. addressing https://github.com/actions/runner/issues/2788
4. typo fix on input for `snok/install-poetry`

minor improvements and fixes for release workflow

---

RLTest/loader.py

store the loaded module in `sys.modules`.
This is a follow-up of #202

Cache modules

---

RLTest/__main__.py

Recent changes that were made on this PR: https://github.com/RedisLabsModules/RLTest/pull/211, changed the way tests results are send to the main processes when parallelism it used. Instead of each processes prints its own output, each processes sends its stdout to the main processes and the main processes prints it. This prevent us from been able to redirect the subprocesses stdout to Redis when using parallelism. Notice that this limitation is not applies when used without parallelism.

Disallow combining parallel execution with --no-output-catch

---

RLTest/__main__.py

- Explicitly set the sub-process start method to `'fork'`, as the default method is different among different OSs, and we rely on forking the memory (local functions, global `Defaults` struct, and more)
- Setting some default values in `_runTest` to be no-op callable so we can always call them (and not have to check if they're `None`)

Set fork as the starting method of a sub-process

---

RLTest/__main__.py

The PR changed the test timeout feature to be applied on a wider range of the test lifetime, including initialization and shutdown.
In order to achieve this, the PR changes the way the timeout works. instead of sleeping for the given amount of timeout, the timeout mechanism now calculate the time on which the timeout will reach and periodically check for the timeout. This allows the test to reset the timeout if needed (for example when running on a class of tests and not on a single function) while the timeout still apply on the entire test lifetime from start to end.

Set timeout of a wider range of the test.

---

RLTest/utils.py

Some environments treat `30` as gray although by the standard it is black
GitHub Actions logs treat it as black, so some messages were very hard to read or even notice.
Fixes:
- `Lgray` wasn't in use (also colors the GB and not the text) - removed
- `Gray` was set to black. Now it is gray (30 -> 90)
check out the standard: https://en.wikipedia.org/wiki/ANSI_escape_code

Fix colors

---

RLTest/redis_std.py

Set `cwd` upon launching redis subprocess to be the logs dir rather than using the `--dir` configuration to set the current dir. 
The motivation for that is when running sanitizer which instruments redis process, the sanitizer creates its log in `cwd` BEFORE redis initializes and sets `cwd` according to the `--dir` configuration. With this change, we can guarantee that logs will always be created in the logs path.

Set cwd in redis process

---

.github/workflows/publish-pypi.yml
.github/workflows/release-drafter.yml

remove broken action and use the [poetry version](https://python-poetry.org/docs/cli/#version) command

Fix release to PyPI flow

---

RLTest/_version.py

This is the first part of a two part fix. pkg_resources exists to help determine the version, in older versions of python. This comes from setuptools, and has since been deprecated. In the case where there is no pkg_resources, for now, we assume we're on master.
Ideally we could rely on metadata, which in turn involves deprecating Python 3.7, or allowing for an import wrapper (see redis-py). Given the number of projects using the current state, this is a lighter weight approach that we could accept now, until we update everything downstream.

Fixing pkg_resources not present

---

.github/workflows/publish-pypi.yml

1. Bumping action versions
2. Removing redundant steps

Fix Release Flow

---

RLTest/debuggers.py
tests/unit/test_debuggers.py

This fixes the issue when the relative path is provided, which causes the process not starting correctly and the tests - failing.

Use the absolute path for the valgrind log file
